# This is system configuration file
#########################################

##################################################
# 
# parameter configuration
#
##################################################

parameters:
  alpha: 0.3
  beta:  0.4
  gama:  0.3
